<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Predicting Real Estate Sale Prices in Oregon: A Data-Driven Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-7189104584608726a80707a12c970cfd.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta name="citation_title" content="Predicting Real Estate Sale Prices in Oregon: A Data-Driven Approach">
<meta name="citation_author" content="Brandon Rodriguez-Hernandez">
<meta name="citation_author" content="Endy Zarate">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_author=RealEstateAPI;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.realestateapi.com/;">
<meta name="citation_reference" content="citation_title=Transaction types - property detail API reference;,citation_author=RealEstateAPI;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://developer.realestateapi.com/reference/transaction-types;">
<meta name="citation_reference" content="citation_title=Determining the sellability of real estate properties in oregon and optimizing the house search for buyers;,citation_author=Brandon Rodriguez-Hernandez;,citation_author=Endy Zarate;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;">
<meta name="citation_reference" content="citation_title=Oregon housing market: Prices, trends, forecast 2024-2025;,citation_author=Redfin;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.redfin.com/state/Oregon/housing-market;">
<meta name="citation_reference" content="citation_title=S&amp;amp;amp;p CoreLogic case-shiller u.s. National home price NSA index;,citation_author=S&amp;amp;P Dow Jones Indices;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.spglobal.com/spdji/en/indices/indicators/sp-corelogic-case-shiller-us-national-home-price-nsa-index/;">
<meta name="citation_reference" content="citation_title=Many first-time homebuyers are pushing 40 as millennials wait in vain for a better market;,citation_author=J. Feng;,citation_author=C. Romans;,citation_publication_date=2025-04-18;,citation_cover_date=2025-04-18;,citation_year=2025;,citation_fulltext_html_url=https://www.nbcnews.com/business/real-estate/many-first-time-homebuyers-are-pushing-40-millennials-wait-vain-better-rcna201786;,citation_journal_title=NBC News;">
<meta name="citation_reference" content="citation_title=Highlights from the profile of home buyers and sellers;,citation_author=National Association of Realtors;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_fulltext_html_url=https://www.nar.realtor/research-and-statistics/research-reports/highlights-from-the-profile-of-home-buyers-and-sellers;">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Predicting Real Estate Sale Prices in Oregon: A Data-Driven Approach</h1>
            <p class="subtitle lead">MSDS Capstone Project</p>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
        
        <div class="quarto-title-meta">

                <div>
            <div class="quarto-title-meta-heading">Authors</div>
            <div class="quarto-title-meta-contents">
                        <p>Brandon Rodriguez-Hernandez </p>
                        <p>Endy Zarate </p>
                      </div>
          </div>
                
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      </div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">Background</a></li>
  <li><a href="#conclusions-future-work" id="toc-conclusions-future-work" class="nav-link" data-scroll-target="#conclusions-future-work">Conclusions &amp; Future Work</a></li>
  <li><a href="#data-acquisition-and-preprocessing" id="toc-data-acquisition-and-preprocessing" class="nav-link" data-scroll-target="#data-acquisition-and-preprocessing">Data Acquisition and Preprocessing</a>
  <ul class="collapse">
  <li><a href="#data-sourcing-and-integration" id="toc-data-sourcing-and-integration" class="nav-link" data-scroll-target="#data-sourcing-and-integration">Data Sourcing and Integration</a></li>
  <li><a href="#data-cleaning-and-filtering" id="toc-data-cleaning-and-filtering" class="nav-link" data-scroll-target="#data-cleaning-and-filtering">Data Cleaning and Filtering</a></li>
  <li><a href="#imputation" id="toc-imputation" class="nav-link" data-scroll-target="#imputation">Imputation</a></li>
  <li><a href="#target-variable-transformation" id="toc-target-variable-transformation" class="nav-link" data-scroll-target="#target-variable-transformation">Target Variable Transformation</a></li>
  </ul></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a>
  <ul class="collapse">
  <li><a href="#stage-1-the-baseline-model" id="toc-stage-1-the-baseline-model" class="nav-link" data-scroll-target="#stage-1-the-baseline-model">Stage 1: The Baseline Model</a></li>
  <li><a href="#stage-2-the-enriched-model" id="toc-stage-2-the-enriched-model" class="nav-link" data-scroll-target="#stage-2-the-enriched-model">Stage 2: The Enriched Model</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#stage-1-the-baseline-model---the-limits-of-physical-attributes" id="toc-stage-1-the-baseline-model---the-limits-of-physical-attributes" class="nav-link" data-scroll-target="#stage-1-the-baseline-model---the-limits-of-physical-attributes">Stage 1: The Baseline Model - The Limits of Physical Attributes</a></li>
  <li><a href="#stage-2-the-enriched-model---the-power-of-context" id="toc-stage-2-the-enriched-model---the-power-of-context" class="nav-link" data-scroll-target="#stage-2-the-enriched-model---the-power-of-context">Stage 2: The Enriched Model - The Power of Context</a></li>
  <li><a href="#discussion-from-simple-metrics-to-complex-insights" id="toc-discussion-from-simple-metrics-to-complex-insights" class="nav-link" data-scroll-target="#discussion-from-simple-metrics-to-complex-insights">Discussion: From Simple Metrics to Complex Insights</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#conclusions-future-work-1" id="toc-conclusions-future-work-1" class="nav-link" data-scroll-target="#conclusions-future-work-1">Conclusions &amp; Future Work</a>
  <ul class="collapse">
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work">Future Work</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">



  


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>For seasoned real estate professionals, the ability to accurately estimate a property’s market value is a cornerstone of their expertise. This intuition, developed over years of experience, provides a significant advantage in a competitive landscape. However, for newcomers, be it first-time homebuyers navigating a complex process or new agents striving to build a successful career, this knowledge is not readily available. This project aims to bridge that knowledge gap of homebuying within Oregon’s dynamic housing market by leveraging data science to move beyond intuition and uncover key, quantifiable drivers of property valuation.</p>
<p>The Oregon housing market provides a compelling and timely case study for this endeavor. The state’s real estate landscape is in a state of flux, characterized by competing signals that can be difficult for non-experts to interpret. In the last year, Oregon has seen a modest 0.3% rise in median home prices, coupled with a significant 7.9% increase in housing supply <span class="citation" data-cites="oregon_market_data">(<a href="#ref-oregon_market_data" role="doc-biblioref">Redfin 2025</a>)</span>. Counterintuitively, the median days on the market has also increased, suggesting a potential cooling or shift in market dynamics. It is within this complex environment that data-driven insights become most valuable.</p>
<p>Due to the conflicting real estate market, first-time home buyers are in a tricky position. They face increasing home prices in competitive and sought after locations while experiencing economic instability and uncertainty from the current administration <span class="citation" data-cites="feng_romans_2025">(<a href="#ref-feng_romans_2025" role="doc-biblioref">Feng and Romans 2025</a>)</span>. Additionally, the rise in interest rates does not ease buyers’ concerns and may lead them to make uninformed purchases in fear that rates may not decline in the future. They may not realize that their desirable features in a home is what is driving a high price point. Perhaps they could have saved money by compromising and leveraging certain characteristics of a property.</p>
<p>The central research question guiding this project is therefore: <strong>Which quantifiable property characteristics in Oregon are the most significant predictors of a residential real estate property’s final sale price?</strong></p>
<p>To answer this question, we undertook a two-stage modeling approach. We first established a Baseline Model using only a property’s intrinsic physical attributes. This initial model, while informative, proved limited in its predictive power. We then developed an Enriched Model that incorporated advanced feature engineering, creating new variables to capture neighborhood context, market seasonality, and property layout efficiencies. By comparing multiple machine learning algorithms, including Ridge Regression, Random Forest, and LightGBM, this approach allowed us to not only dramatically improve predictive accuracy but, more importantly, to interpret the complex interplay of factors that determine a home’s ultimate value. Utilizing our findings, we are able to give general recommendations to first-time home buyers in Oregon.</p>
</section>
<section id="background" class="level1">
<h1>Background</h1>
<p>Given the current Oregon real estate market and the economic instability, first-time home buyers are becoming increasingly older and rarer. As shown in Figure 1, the median age of the first-time home owner is 38 years old <span class="citation" data-cites="nar_2024">(<a href="#ref-nar_2024" role="doc-biblioref">National Association of Realtors 2024</a>)</span>.</p>
<div id="fig-median-age" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-median-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-median-age" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-age" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="plot.png" class="lightbox" data-gallery="fig-median-age" title="Figure&nbsp;1&nbsp;(a): Median Age of First-Time Homeowners Over the Past 22 Years. The median age of the first-time home owner was fairly consistent for the past 22 years until recent times. Last year’s increase was the highest percentage increase (8%) in the current century."><img src="plot.png" class="img-fluid figure-img" data-ref-parent="fig-median-age"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Median Age of First-Time Homeowners Over the Past 22 Years. The median age of the first-time home owner was fairly consistent for the past 22 years until recent times. Last year’s increase was the highest percentage increase (8%) in the current century.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-median-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
<p>The median age has increased by three years from last year’s median age of 35. Since 2020, the incline has been sharp. If the current median first-time home owner takes the standard 30-year mortgage, they will be paying it off well into retirement. With stock market volatility impacting 401(k)s and ongoing discussions about the future of Social Security, becoming a first-time homeowner at the current median age is an increasingly risky financial decision. Given those issues, first-time home owners are becoming uncommon. First-time home owners make up about 24% of all buyers which is down from last year’s 32% <span class="citation" data-cites="nar_2024">(<a href="#ref-nar_2024" role="doc-biblioref">National Association of Realtors 2024</a>)</span>.</p>
<p>The median household income for the first-time homeowner has increased to $97,000 <span class="citation" data-cites="nar_2024">(<a href="#ref-nar_2024" role="doc-biblioref">National Association of Realtors 2024</a>)</span>. Additionally, 73% of all home buyers do not have a child aged 3 or younger. There is a small portion of home buyers that seek out multigenerational homes. Their main reasoning for that is cost savings. They have elderly parents to take care of, children that are moving back home and kids that do not leave the home once they reach adulthood These statistics and reasoning point to rising home prices. Oregon home prices may have only increased by 0.3% in the last year but they have increased significantly in the last five years. The reason for the increase in property value is unfamiliar to the average person or home buyer.</p>
<p>The process of determining a property’s value is not conducted in a vacuum; it is deeply embedded within the context of the broader real estate market, which is itself influenced by a host of economic forces. To understand the significance of predicting a single property’s price, one must first appreciate the macro-level indicators that define the health and trajectory of the market as a whole.</p>
<p>A key metric for this high-level view is the S&amp;P CoreLogic Case-Shiller Home Price Index, a well-regarded barometer that tracks changes in residential real estate values to gauge market trends nationally and regionally <span class="citation" data-cites="case_shiller_index">(<a href="#ref-case_shiller_index" role="doc-biblioref">S&amp;P Dow Jones Indices 2025</a>)</span>. While such indices are invaluable for understanding broad market movements, for instance, telling us if the Portland metropolitan area market is generally heating up or cooling down, they do not and cannot explain the price variability at the individual property level. A rising index does not clarify why two similar-sized homes on the same street might sell for vastly different prices. This is the analytical gap our research aims to fill.</p>
<p>Our project operates on the premise that while market-wide forces set a general price level, the specific, measurable characteristics of a property and its immediate surroundings are what determine its value within that market. We move from a macro to a micro-level analysis to isolate the features that drive these price differences. These features can be grouped into several key domains:</p>
<ul>
<li><strong>Physical Attributes:</strong> These are the most intuitive value drivers, including the property’s Living Area (in square feet), the number of Bedrooms and Bathrooms, the total Lot Size, and the Property’s Age.</li>
<li><strong>Geographical Context:</strong> The classic real estate mantra of “location, location, location” is represented by geographical features like a property’s City and Zip Code. A property’s location dictates its proximity to amenities, school districts, and employment centers, all of which have a profound impact on its desirability and value.</li>
<li><strong>Socio-Economic Environment:</strong> The financial health of a community, captured by data such as the local Median Household Income, provides crucial context. A strong local economy can bolster property values, while economic distress can suppress them.</li>
<li><strong>Regulatory Environment:</strong> Factors like local Zoning laws (which dictate what can be built on the property) provide a formal framework that constrains and defines a property’s use.</li>
</ul>
<p>By building a statistical model that incorporates features from all these domains, we can effectively deconstruct a final sale price into its component parts. The goal is to quantify the impact of each individual feature: How much value does an extra bathroom add, on average? What is the price premium for a home in Portland versus one in Eugene? This data-driven approach provides a structured, evidence-based alternative to the years of hard-won intuition, creating a tool that can empower first-time home buyers to better understand the forces shaping the Oregon real estate market.</p>
</section>
<section id="conclusions-future-work" class="level1">
<h1>Conclusions &amp; Future Work</h1>
<p>A commitment to ethical practice was paramount throughout this project. Before detailing our methodology, it is essential to frame our work within the ethical dimensions of data handling, algorithmic fairness, and responsible use.</p>
<ul>
<li><strong>Privacy and Data Handling:</strong> We have prioritized individual privacy by exclusively using property-level data. While the raw data source contained personally identifiable information such as owner names, this information was explicitly excluded from our analytical dataset at the earliest stage. Our focus remained squarely on the structural, transactional, and geographical characteristics of the properties themselves, the <em>what</em> and <em>where</em>, not the <em>who</em>.</li>
<li><strong>Algorithmic Bias and Fairness:</strong> We acknowledge that real estate data is not neutral; it is a social artifact that can reflect and perpetuate historical societal biases. An algorithm trained on this data could inadvertently learn and amplify these patterns. We recognize that historical sale prices are a product of market forces that may include discriminatory practices. We therefore present our model’s predictions not as an objective truth, but as a reflection of the patterns present in the available historical data.</li>
<li><strong>Transparency and Responsible Use:</strong> Recognizing the potential for misuse, we emphasize that this model is intended as an informational tool, not as a definitive arbiter of property value or as a replacement for professional appraisal. With a final Mean Absolute Error of approximately $84,000, the predictions should be understood as data-driven estimates with a known margin of error. The model’s output should be interpreted as a ballpark estimate or a data-driven starting point for further research, not as a precise quote.</li>
</ul>
</section>
<section id="data-acquisition-and-preprocessing" class="level1">
<h1>Data Acquisition and Preprocessing</h1>
<p>The foundation of this analysis rests upon the systematic acquisition and meticulous preparation of a complex, multi-source dataset.</p>
<section id="data-sourcing-and-integration" class="level3">
<h3 class="anchored" data-anchor-id="data-sourcing-and-integration">Data Sourcing and Integration</h3>
<p>The data for this project was sourced from the RealEstateAPI <span class="citation" data-cites="realestateapi_main">(<a href="#ref-realestateapi_main" role="doc-biblioref">RealEstateAPI 2025b</a>)</span>, a comprehensive platform providing granular real estate data. The core dataset, containing sales transactions, was strategically enriched with data from four other key tables: Property Information, Lot Information, Tax Information, and Demographics. A critical methodological decision was the explicit exclusion of certain datasets, such as those containing official Assessed Value, as this would constitute target leakage and lead to a misleadingly accurate model.</p>
</section>
<section id="data-cleaning-and-filtering" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-and-filtering">Data Cleaning and Filtering</h3>
<p>Before cleaning the dataset, we wanted to conduct some exploratory data analysis to understand what was happening in our data and to check that it was read-in correctly.</p>
<p>We noticed an interesting feature in our dataset called <code>property_use</code> which defined the primary usage of each property. With a simple SQL code, we were able to see the unique values in that column. Then, we noticed that not all properties in our dataset would be relevant to our analysis. As shown in Figure 2, in our dataset, there exists numerous properties that are not suitable for first-time home buyers. These properties include parking lots, restaurant spaces, agricultural land and much more. We determined that, since our project focuses on interests of first-time home buyers, we should run our analysis and models on single family residential properties.</p>
<div id="fig-property-use" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-property-use-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-property-use" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-prop-use" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-prop-use-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="filter_error.png" class="lightbox" data-gallery="fig-property-use" title="Figure&nbsp;2&nbsp;(a): Count of Single Family Residential Properties Against Other Uses. There are over 20,000 properties in our dataset that are not single family residential properties which are our main focus. Null values appear in a very small amount of properties."><img src="filter_error.png" class="img-fluid figure-img" data-ref-parent="fig-property-use"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-prop-use-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Count of Single Family Residential Properties Against Other Uses. There are over 20,000 properties in our dataset that are not single family residential properties which are our main focus. Null values appear in a very small amount of properties.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-property-use-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2
</figcaption>
</figure>
</div>
<p>While a large portion of our initial data was not relevant to our analysis, we still had thousands of observations and properties to work with. Therefore, the data was filtered to include only Single-Family Homes and arms-length transactions. Arms-length transactions are fair market sales between unrelated parties <span class="citation" data-cites="realestateapi_docs">(<a href="#ref-realestateapi_docs" role="doc-biblioref">RealEstateAPI 2025a</a>)</span>. By filtering on those transactions, we can remove some of the bias in our dataset as transactions between related parties may undermine the prices of the current market. After removing records with invalid data, the dataset contained 21,720 unique sale records.</p>
</section>
<section id="imputation" class="level3">
<h3 class="anchored" data-anchor-id="imputation">Imputation</h3>
<p>A significant challenge was the presence of missing values. Instead of dropping incomplete rows, a robust imputation strategy was implemented. Missing numerical values were filled using a statistically sound median-based approach, while missing categorical data was filled with the label ‘Unknown’. This approach allowed us to preserve the vast majority of our collected data.</p>
</section>
<section id="target-variable-transformation" class="level3">
<h3 class="anchored" data-anchor-id="target-variable-transformation">Target Variable Transformation</h3>
<p>We shifted our exploratory data analysis to our target variable to check on any concerning insights. As shown on Figure 3, our <code>sale_amount</code> target variable had a large range.</p>
<div id="fig-sale-dist" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sale-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-sale-dist" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-sale-dist-full" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-sale-dist-full-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="skew.png" class="lightbox" data-gallery="fig-sale-dist" title="Figure&nbsp;3&nbsp;(a): A Histogram Distribution of our Target Variable, Sale Amount. The range of sale_amount is huge. There are several properties that have sold for over $2 million dollars."><img src="skew.png" class="img-fluid figure-img" data-ref-parent="fig-sale-dist"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-sale-dist-full-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) A Histogram Distribution of our Target Variable, Sale Amount. The range of sale_amount is huge. There are several properties that have sold for over $2 million dollars.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-sale-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3
</figcaption>
</figure>
</div>
<p>The range seems atypical for single family residential properties. There are numerous outliers in our data and it is concerning that it is spread out among the millions of dollars as it might create a bias in our data. We explored deeper into this matter by zooming in to the histogram as shown in Figure 4.</p>
<div id="fig-sale-zoom" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sale-zoom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-sale-zoom" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-sale-dist-zoom" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-sale-dist-zoom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="outliers.png" class="lightbox" data-gallery="fig-sale-zoom" title="Figure&nbsp;4&nbsp;(a): An Enhanced Histogram Distribution of our Target Variable, Sale Amount. Data is right-skewed despite the large amount of outliers."><img src="outliers.png" class="img-fluid figure-img" data-ref-parent="fig-sale-zoom"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-sale-dist-zoom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) An Enhanced Histogram Distribution of our Target Variable, Sale Amount. Data is right-skewed despite the large amount of outliers.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-sale-zoom-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4
</figcaption>
</figure>
</div>
<p>This revealed a strong positive right skew in the Sale Amount variable that it undermines Oregon’s housing market. To meet the assumptions of regression modeling, a logarithmic transformation (<code>np.log1p</code>) was applied, resulting in a normalized distribution suitable for analysis.</p>
</section>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<p>Our analysis was structured in two stages to clearly demonstrate the value of advanced feature engineering <span class="citation" data-cites="project_proposal">(<a href="#ref-project_proposal" role="doc-biblioref">Rodriguez-Hernandez and Zarate 2025</a>)</span>.</p>
<section id="stage-1-the-baseline-model" class="level3">
<h3 class="anchored" data-anchor-id="stage-1-the-baseline-model">Stage 1: The Baseline Model</h3>
<p>The initial stage focused on creating a simple, interpretable baseline.</p>
<ul>
<li><strong>Features:</strong> This model was trained using only five core physical attributes: Living Area, Lot Size, Bedrooms, Bathrooms, and Property Age.</li>
<li><strong>Model:</strong> A standard RandomForestRegressor was used to establish a performance benchmark.</li>
</ul>
</section>
<section id="stage-2-the-enriched-model" class="level3">
<h3 class="anchored" data-anchor-id="stage-2-the-enriched-model">Stage 2: The Enriched Model</h3>
<p>The second stage aimed to maximize predictive power by creating a rich set of contextual features.</p>
<ul>
<li><p><strong>Advanced Feature Engineering:</strong> We engineered several new categories of features:</p>
<ul>
<li><strong>Time-Based Features:</strong> <code>sale_month</code> and <code>sale_quarter</code> were extracted to capture market seasonality.</li>
<li><strong>Ratio Features:</strong> <code>bathroom-to-bedroom</code> ratio and <code>garage-to-living-area</code> ratio were created to provide insights into property layout and utility.</li>
<li><strong>Neighborhood Aggregate Features:</strong> In a crucial step to prevent data leakage, a custom transformer was built into our pipeline. This transformer calculates the median living area and median property age for each zip code using only the training data and then maps these values to the test set. This provides powerful, and localized context for each property.</li>
</ul></li>
<li><p><strong>Model Selection:</strong> We implemented a comparative approach using three distinct algorithms:</p>
<ul>
<li><strong>Ridge Regression:</strong> A regularized linear model serving as a robust, enhanced baseline.</li>
<li><strong>Random Forest Regressor:</strong> A powerful ensemble model effective at capturing non-linear relationships.</li>
<li><strong>LightGBM Regressor:</strong> A highly efficient, state-of-the-art gradient boosting model, often considered the industry standard for tabular data.</li>
</ul></li>
<li><p><strong>Model Training and Validation:</strong> The dataset was partitioned into an 80% training set and a 20% testing set. All models were trained within a scikit-learn Pipeline that handled all preprocessing steps, including imputation, scaling, and encoding, to ensure a robust and leak-proof workflow. Hyperparameter tuning was performed using GridSearchCV and RandomizedSearchCV.</p></li>
<li><p><strong>Evaluation Metrics:</strong> Model performance was quantified using two standard metrics: R-squared (<span class="math inline">\(R^2\)</span>), which measures the proportion of price variance explained by the model, and Mean Absolute Error (MAE), which provides the average prediction error in dollars.</p></li>
</ul>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>The two-stage analysis yielded a clear and compelling narrative about the power of contextual data.</p>
<section id="stage-1-the-baseline-model---the-limits-of-physical-attributes" class="level3">
<h3 class="anchored" data-anchor-id="stage-1-the-baseline-model---the-limits-of-physical-attributes">Stage 1: The Baseline Model - The Limits of Physical Attributes</h3>
<p>The baseline model, relying only on physical attributes, produced modest results. The top performing model for this dataset was the Random Forest Regressor.</p>
<ul>
<li><strong>Performance:</strong> It achieved an R-squared of 0.327, explaining just under a third of the price variance. The Mean Absolute Error was $136,414.</li>
<li><strong>Feature Importance:</strong> The model’s feature importance plot (Figure 5) shows that it relied almost exclusively on Living Area and Property Age. This result highlights a fundamental flaw: the model treats a 2,000-square-foot house in a high-income Portland suburb identically to one in a rural, low-income area. This lack of context is the primary reason for its limited accuracy.</li>
</ul>
<div id="fig-baseline-importance" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-baseline-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-baseline-importance" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-baseline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-baseline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="baseline_feature_importances.png" class="lightbox" data-gallery="fig-baseline-importance" title="Figure&nbsp;5&nbsp;(a): Baseline Model Feature Importances. In a model using only physical attributes, Living Area is the overwhelmingly dominant predictor."><img src="baseline_feature_importances.png" class="img-fluid figure-img" data-ref-parent="fig-baseline-importance"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-baseline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Baseline Model Feature Importances. In a model using only physical attributes, Living Area is the overwhelmingly dominant predictor.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-baseline-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5
</figcaption>
</figure>
</div>
</section>
<section id="stage-2-the-enriched-model---the-power-of-context" class="level3">
<h3 class="anchored" data-anchor-id="stage-2-the-enriched-model---the-power-of-context">Stage 2: The Enriched Model - The Power of Context</h3>
<p>The introduction of advanced features led to a dramatic and unequivocal improvement in performance. The final results for the enriched models are summarized in Table 1.</p>
<p><strong>Table 1: Enriched Model Performance on Test Data</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 28%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Test R-squared (<span class="math inline">\(R^2\)</span>)</th>
<th style="text-align: left;">Test Mean Absolute Error (MAE)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LightGBM Regressor</td>
<td style="text-align: left;">0.632</td>
<td style="text-align: left;">$84,255</td>
</tr>
<tr class="even">
<td style="text-align: left;">RandomForest Regressor</td>
<td style="text-align: left;">0.611</td>
<td style="text-align: left;">$89,591</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ridge Regression</td>
<td style="text-align: left;">0.476</td>
<td style="text-align: left;">$113,377</td>
</tr>
</tbody>
</table>
<p>The best-performing model, LightGBM, achieved an R-squared of 0.632, nearly doubling the explanatory power of the baseline. The MAE dropped by over $52,000 to just $84,255. This substantial improvement is a direct result of providing the model with the necessary context. The most compelling evidence comes from the new feature importance plot (Figure 6).</p>
<div id="fig-enriched-importance" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-enriched-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-enriched-importance" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-enriched" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-enriched-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="enriched_feature_importances.png" class="lightbox" data-gallery="fig-enriched-importance" title="Figure&nbsp;6&nbsp;(a): Enriched Model Feature Importances. With contextual data, the model’s focus shifts. While Living Area remains critical, engineered features like Neighborhood Median Area and Property Age now play a much more significant role."><img src="enriched_feature_importances.png" class="img-fluid figure-img" data-ref-parent="fig-enriched-importance"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-enriched-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Enriched Model Feature Importances. With contextual data, the model’s focus shifts. While Living Area remains critical, engineered features like Neighborhood Median Area and Property Age now play a much more significant role.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-enriched-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6
</figcaption>
</figure>
</div>
</section>
<section id="discussion-from-simple-metrics-to-complex-insights" class="level3">
<h3 class="anchored" data-anchor-id="discussion-from-simple-metrics-to-complex-insights">Discussion: From Simple Metrics to Complex Insights</h3>
<p>The journey from the Baseline to the Enriched Model tells a clear story. The rise of engineered features like Median Neighborhood Area and the continued importance of Property Age and Living Area in the feature importance plot is the key finding of this research. It provides quantitative proof that the socio-economic health of a neighborhood and its defining characteristics are just as critical as the physical structure of the house itself. The model learned that a smaller home in a desirable neighborhood is often worth more than a larger home in a less sought-after area. In essence, the supplementary data provided the <em>why</em> behind the price.</p>
</section>
</section>
<section id="limitations" class="level1">
<h1>Limitations</h1>
<p>While this study successfully developed a methodologically sound model, it is crucial to acknowledge its limitations. The final R-squared value of 0.632 indicates that approximately 37% of the variability in Oregon’s home prices remains unexplained by our model. This is not a failure but an important finding about the inherent complexity of the real estate market. Several factors contribute to this:</p>
<ul>
<li><strong>Unobserved Variables (The Last Mile Problem):</strong> Our dataset does not capture critical factors like interior condition, quality of finishes, recent renovations, or curb appeal. These variables constitute a significant portion of the remaining unexplained variance.</li>
<li><strong>Market Dynamics and Human Factors:</strong> A final sale price is the result of a negotiation influenced by factors like seller motivation, buyer sentiment, and the specific competitive landscape at the moment of sale. These elements are highly stochastic and cannot be fully captured by static features.</li>
<li><strong>Data Granularity:</strong> While we incorporated zip code-level data, more granular information, such as specific school district ratings or hyper-local crime statistics, could further improve performance.</li>
</ul>
</section>
<section id="conclusions-future-work-1" class="level1">
<h1>Conclusions &amp; Future Work</h1>
<p>This research successfully developed a predictive model that explains 63.2% of the variance in Oregon real estate sale prices. Our iterative modeling process demonstrated that while a property’s physical attributes provide a reasonable baseline, the most significant gains in predictive power come from advanced feature engineering, particularly the creation of features that provide local neighborhood context.</p>
<p>The primary conclusion is that a property’s value is a multifaceted interplay between its physical attributes (led by Living Area), its geographical context (powerfully captured by our engineered neighborhood statistics), and its age. The journey from a model that could only explain 33% of price variance to one that could explain over 63% is a powerful, quantitative confirmation of the real estate axiom that value is determined by more than just the house itself.</p>
<p>First-time home buyers should take into consideration the most influential property factors when researching home listings and before making purchase decisions. Living area was the most significant indicator of final sale price in our dataset. Housing prices are high and continue to climb so first-time home buyers can take solace in the fact that they can opt for a cheaper and smaller home without compromising on other desired features such as bedroom or bathroom count. Newer properties have higher sale prices as well as properties from affluent neighborhoods.</p>
<p>These important indicators have complex relationships with each other and several other factors that we could not include in our analysis. It is up to the first time home buyer to decide what property characteristics truly matter to them. Perhaps they will come to the conclusion they need to increase their search budget. While the median age of the first time home owner remains high, knowledge about the current real estate market is something within the control of the buyer and it is their most powerful tool as they approach the important milestone of home buying.</p>
<section id="future-work" class="level3">
<h3 class="anchored" data-anchor-id="future-work">Future Work</h3>
<p>Several avenues for future research are apparent:</p>
<ul>
<li><strong>Survival Analysis for Time on Market:</strong> The next logical step is to conduct a survival analysis to model the time a property spends on the market, addressing not only <em>how much?</em> but also <em>how long?</em>.</li>
<li><strong>Incorporate Time-Series Data:</strong> Incorporating time-series data, such as historical interest rates or changes in local housing inventory, would allow the model to adapt to changing market conditions.</li>
<li><strong>Granular Geospatial Features:</strong> To address the unobserved variables limitation, future iterations could benefit from integrating data on specific school district ratings, proximity to parks, or local crime rates to capture neighborhood-level nuances and further enhance predictive accuracy.</li>
</ul>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-feng_romans_2025" class="csl-entry" role="listitem">
Feng, J., and C. Romans. 2025. <span>“Many First-Time Homebuyers Are Pushing 40 as Millennials Wait in Vain for a Better Market.”</span> NBC News. April 18, 2025. <a href="https://www.nbcnews.com/business/real-estate/many-first-time-homebuyers-are-pushing-40-millennials-wait-vain-better-rcna201786">https://www.nbcnews.com/business/real-estate/many-first-time-homebuyers-are-pushing-40-millennials-wait-vain-better-rcna201786</a>.
</div>
<div id="ref-nar_2024" class="csl-entry" role="listitem">
National Association of Realtors. 2024. <span>“Highlights from the Profile of Home Buyers and Sellers.”</span> 2024. <a href="https://www.nar.realtor/research-and-statistics/research-reports/highlights-from-the-profile-of-home-buyers-and-sellers">https://www.nar.realtor/research-and-statistics/research-reports/highlights-from-the-profile-of-home-buyers-and-sellers</a>.
</div>
<div id="ref-realestateapi_docs" class="csl-entry" role="listitem">
RealEstateAPI. 2025a. <span>“Transaction Types - Property Detail API Reference.”</span> 2025. <a href="https://developer.realestateapi.com/reference/transaction-types">https://developer.realestateapi.com/reference/transaction-types</a>.
</div>
<div id="ref-realestateapi_main" class="csl-entry" role="listitem">
———. 2025b. 2025. <a href="https://www.realestateapi.com/">https://www.realestateapi.com/</a>.
</div>
<div id="ref-oregon_market_data" class="csl-entry" role="listitem">
Redfin. 2025. <span>“Oregon Housing Market: Prices, Trends, Forecast 2024-2025.”</span> 2025. <a href="https://www.redfin.com/state/Oregon/housing-market">https://www.redfin.com/state/Oregon/housing-market</a>.
</div>
<div id="ref-project_proposal" class="csl-entry" role="listitem">
Rodriguez-Hernandez, Brandon, and Endy Zarate. 2025. <span>“Determining the Sellability of Real Estate Properties in Oregon and Optimizing the House Search for Buyers.”</span>
</div>
<div id="ref-case_shiller_index" class="csl-entry" role="listitem">
S&amp;P Dow Jones Indices. 2025. <span>“S&amp;p CoreLogic Case-Shiller u.s. National Home Price NSA Index.”</span> 2025. <a href="https://www.spglobal.com/spdji/en/indices/indicators/sp-corelogic-case-shiller-us-national-home-price-nsa-index/">https://www.spglobal.com/spdji/en/indices/indicators/sp-corelogic-case-shiller-us-national-home-price-nsa-index/</a>.
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>